### ISSUE TITLE
Figwheel Server: Resource not found

### ISSUE THREAD

**Issue by mgerlach-klick** [reagent-project/reagent-frontend-template#1]
Creating a new project and running `lein figwheel` and going to http://localhost:3449 results in a page stating 
"Figwheel Server: Resource not found
Keep on figwheelin'"

**Comment by yogthos** [comment]
There isn't an http server anymore, you should be able to go to index.html in the public folder and open it in the browser.

**Comment by mgerlach-klick** [comment]
Yeah that works - maybe that should go into the readme?

**Comment by yogthos** [comment]
Yeah definitely :-)

**Comment by mgerlach-klick** [comment]
Thank you though, I'm very happy with this :)

**Comment by yogthos** [comment]
glad to hear it, and fixed the docs :)

**Comment by rosenk** [comment]
@yogthos I was inspired from your post in [https://news.ycombinator.com/item?id=12189673](https://news.ycombinator.com/item?id=12189673) and ended up here :) not that great experience after all. Please help.

> There isn't an http server anymore, you should be able to go to index.html in the public folder and open it in the browser.

What that suppose to mean? What is the exact address?
[http://127.0.0.1:3449/public/index.html](http://127.0.0.1:3449/public/index.html) Dosn't work !

**Comment by yogthos** [comment]
The front-end version of the template doesn't run an HTTP server. You simply open the `index.html` file found in the `public` folder of the generated project in the browser.

For example, if you create a project by running `lein new reagent-frontend myapp`, you'll have `myapp/public/index.html`. If you're still having trouble check the following things to troubleshoot:

Make  sure that you have [JDK8](http://www.azul.com/downloads/zulu/) and latest [Leiningen](http://leiningen.org/) installed:

```
>javac -version
javac 1.8.0_40
>lein version
Leiningen 2.7.0 on Java 1.8.0_40 Java HotSpot(TM) 64-Bit Server VM
```

(Leiningen 2.6.1+ should work fine)

If you have that, then make sure the project is created by running:

```
lein new reagent-frontend myapp
```

go to the folder

   cd myapp

start Figwheel

```
lein figwheel
```

Once it starts, you should see the following prompt:

```
lein figwheel
Figwheel: Cleaning because dependencies changed
Figwheel: Cutting some fruit, just a sec ...
Figwheel: Validating the configuration found in project.clj
Figwheel: Configuration Valid :)
Figwheel: Starting server at http://0.0.0.0:3449
Figwheel: Watching build - app
Figwheel: Cleaning build - app
Compiling "public/js/app.js" from ["src" "env/dev/cljs"]...
Successfully compiled "public/js/app.js" in 14.124 seconds.
Figwheel: Starting CSS Watcher for paths  ["public/css"]
Figwheel: Starting nREPL server on port: 7002
Launching ClojureScript REPL for build: app
Figwheel Controls:
          (stop-autobuild)                ;; stops Figwheel autobuilder
          (start-autobuild [id ...])      ;; starts autobuilder focused on optional ids
          (switch-to-build id ...)        ;; switches autobuilder to different build
          (reset-autobuild)               ;; stops, cleans, and starts autobuilder
          (reload-config)                 ;; reloads build config and resets autobuild
          (build-once [id ...])           ;; builds source one time
          (clean-builds [id ..])          ;; deletes compiled cljs target files
          (print-config [id ...])         ;; prints out build configurations
          (fig-status)                    ;; displays current state of system
  Switch REPL build focus:
          :cljs/quit                      ;; allows you to switch REPL to another build
    Docs: (doc function-name-here)
    Exit: Control+C or :cljs/quit
 Results: Stored in vars *1, *2, *3, *e holds last exception object
Prompt will show when Figwheel connects to your application
```

At this point the app is compiled and you should be able to open the `public/index.html` file in the browser.

**Comment by rosenk** [comment]
Thanks, it works now. I had trouble figuring out that I must open an file:// in the browser. what figweel starts at 
`Figwheel: Starting server at http://0.0.0.0:3449`
is beyond me.

**Comment by yogthos** [comment]
The server that figwheel starts is used to recompile and hotload code in the browser during development. Any changes you make in the source files should be reflected in the running app while figwheel is running.
