### ISSUE TITLE
Template resource not found error

### ISSUE THREAD

**Issue by jamesdavidson** [reagent-project/reagent-frontend-template#10]
Hi,

First of all, I am a huge Reagent fan. Thanks so much for your time and effort!

I just tried to create a new project but got a "Template resource not found" error. I only have this problem with v0.1.34, not v0.1.33. Here are the **lein** commands I ran and their output.

```
$ lein new reagent-frontend com.example --template-version 0.1.33
Generating fresh 'lein new' Reagent frontend project.
$ rm -rf com.example
$ lein new reagent-frontend com.example --template-version 0.1.34
Generating fresh 'lein new' Reagent frontend project.
Template resource 'leiningen/new/reagent_frontend/env/dev/clj/user.clj' not found.
```

Thanks,
James

**Comment by yogthos** [comment]
Thanks for the heads up, looks like I forgot to checkin the `user.clj` file. Just pushed out a new version with the fix, let me know if everything looks good.

**Comment by jamesdavidson** [comment]
I have just installed v0.1.35 and it is working a treat. Thanks again!
