### ISSUE TITLE
Stacktrace when connecting cljs repl

### ISSUE THREAD

**Issue by harold** [reagent-project/reagent-frontend-template#18]
First, thanks for this excellent template, I often need to try out reagent things in a clean, empty, environment for experimentation. Having an up-to-date template like this is a huge time-saver.

---

Here are the steps I'm doing that are resulting in the stacktrace:

1) `lein new reagent-frontend reagent-frontend-test +figwheel`

This works well

2) In emacs, I do `cider-jack-in`

The repl starts:

```clj
;; Connected to nREPL server - nrepl://localhost:34185
;; CIDER 1.5.0 (Strasbourg), nREPL 1.0.0
;; Clojure 1.11.1, Java 11.0.17
;;     Docs: (doc function-name)
;;           (find-doc part-of-name)
;;   Source: (source function-name)
;;  Javadoc: (javadoc java-object-or-class)
;;     Exit: <C-c C-q>
;;  Results: Stored in vars *1, *2, *3, an exception in *e;
;;  Startup: /home/harold/bin/lein update-in :dependencies conj \[nrepl/nrepl\ \"0.9.0\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.28.5\"\] -- repl :headless :host localhost
```

3) Then I call `(start-fw)`:

Which appears to work well:

```clj
user> (start-fw)
Figwheel: Starting server at http://0.0.0.0:3449
Figwheel: Watching build - app
Figwheel: Cleaning build - app
Compiling build :app to "public/js/app.js" from ["src" "env/dev/cljs"]...
Successfully compiled build :app to "public/js/app.js" in 0.392 seconds.
Figwheel: Starting CSS Watcher for paths  ["public/css"]
Figwheel: Starting nREPL server on port: 7002
nil
```

4) Then I call `(cljs)`:

And I see this stacktrace:

```clj
Launching ClojureScript REPL for build: app
Figwheel Controls:
          (stop-autobuild)                ;; stops Figwheel autobuilder
          (start-autobuild id ...)        ;; starts autobuilder focused on optional ids
          (switch-to-build id ...)        ;; switches autobuilder to different build
          (reset-autobuild)               ;; stops, cleans, and starts autobuilder
          (reload-config)                 ;; reloads build config and resets autobuild
          (build-once id ...)             ;; builds source one time
          (clean-builds id ..)            ;; deletes compiled cljs target files
          (print-config id ...)           ;; prints out build configurations
          (fig-status)                    ;; displays current state of system
          (figwheel.client/set-autoload false)    ;; will turn autoloading off
          (figwheel.client/set-repl-pprint false) ;; will turn pretty printing off
  Switch REPL build focus:
          :cljs/quit                      ;; allows you to switch REPL to another build
    Docs: (doc function-name-here)
    Exit: :cljs/quit
 Results: Stored in vars *1, *2, *3, *e holds last exception object
Prompt will show when Figwheel connects to your application
Exception in thread "Thread-19" java.lang.NullPointerException
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1134)
	at clojure.core$re_matcher.invokeStatic(core.clj:4881)
	at clojure.core$re_find.invokeStatic(core.clj:4923)
	at clojure.core$re_find.invoke(core.clj:4923)
	at cljs.analyzer$analyze_file.invokeStatic(analyzer.cljc:4862)
	at cljs.analyzer$analyze_file.invoke(analyzer.cljc:4838)
	at cljs.analyzer$analyze_file.invokeStatic(analyzer.cljc:4852)
	at cljs.analyzer$analyze_file.invoke(analyzer.cljc:4838)
	at cljs.analyzer$analyze_file.invokeStatic(analyzer.cljc:4848)
	at cljs.analyzer$analyze_file.invoke(analyzer.cljc:4838)
	at cljs.repl$repl_STAR_$fn__8067$fn__8068$fn__8071.invoke(repl.cljc:1181)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:671)
	at clojure.core$bound_fn_STAR_$fn__5818.doInvoke(core.clj:2020)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:829)
nil
To quit, type: :cljs/quit
```

---

I see the same stacktrace if I used `cider-jack-in-cljs` instead of `cider-jack-in`.

---

I dug in a bit, and it seems that `repl*` in `repl.cljc` is trying to call `analyze-file` on the `:main` ns (`reagent-frontend-test.dev`) that is specified in the `project.clj`, but `io/resource` is returning `nil`, and so `analyze-file` ends up throwing.

---

I am no expert in these matters, but it would be nice, for me, to have the cljs repl in cider rather than in a separate terminal window (as when I do `lein figwheel`, which works well).

I suspect I'm either doing something silly, or have the wrong version of something. Let me know what else I can do or provide to help track this down.

Thanks in advance for your time and consideration.

**Comment by yogthos** [comment]
I'd have to dig a bit into what figwheel is doing, but is there a reason not to use shadow-cljs in the meantime?

**Comment by harold** [comment]
Thanks for the quick reply!

> is there a reason not to use shadow-cljs in the meantime?
>

No. And also, I am not blocked (I can use `lein figwheel` in a separate terminal for now). :slightly_smiling_face: 

For what it's worth, my company does everything with lein, and figwheel (we do not use shadow-cljs, yet). That's why I chose the figwheel path when trying this template (I am much more familiar with figwheel), so I appreciate the figwheel version of this template existing.

**Comment by yogthos** [comment]
Ah I see, makes sense if you're already doing things with figwheel. I ended up switching to shadow-cljs because it plays well with NPM ecosystem, and haven't touched figwheel for a while as a result. The error looks like it's a classpath issue where `test` folder might be missing in the `project.clj` config.

**Comment by harold** [comment]
>  The error looks like it's a classpath issue where test folder might be missing in the project.clj config.

That sounds possible!

Two questions:
1) Do you know how to inspect the classpath that is in use in Cider?
 - That would certainly help track down the problem

2) I believe the problem is related to the `env/dev/cljs/reagent-frontend-test/dev.cljs` file...
 - I see `:source-paths ["src" "env/dev/cljs"]` which presumably is putting that file on the classpath, but..

**Comment by yogthos** [comment]
It might be worth trying to add `test` to `:source-paths` to see if that might help. Not sure how to get Cider to print classpath though, I presume it would build it based on the source-paths declared in project.clj.

**Comment by harold** [comment]
Adding `"test"` to source paths was a neat idea, but it didn't change anything.

However, you gave me a good idea, I tried adding `"env/dev/cljs"` to `:profiles {:dev {:source-paths [...` and the error went away.

So, yeah, it looks like maybe the `:main` namespace in the cljsbuild compiler options needs to be on the classpath for the cider cljs repl to start. Again, I'm no expert.

So, I guess the proposed change would be to add `"env/dev/cljs"` to this line: https://github.com/reagent-project/reagent-frontend-template/blob/master/resources/leiningen/new/reagent_frontend/project.clj#L53

Not sure if this is a great idea for everyone or not, but it does seem to get the cider cljs repl to start cleanly.

Thanks again for your help and time, and for maintaining this template.

**Comment by yogthos** [comment]
Ah yeah that makes sense, and glad we got this figured out. I'll take a look at updating the template to make this work out of the box going forward.

**Comment by harold** [comment]
Neat! Thanks.

**Comment by yogthos** [comment]
Just pushed out a new version, let me know if everything looks good on your end.

**Comment by harold** [comment]
Created a new project from scratch just now and I can confirm that both the `cider-jack-in-cljs` pathway, and the `lein figweel` in the terminal pathway are working well for me.

Others may still use this in other ways, but for me it's working.
