### ISSUE TITLE
React 18 warning

### ISSUE THREAD

**Issue by harold** [reagent-project/reagent-frontend-template#19]
When the app starts, I see this warning in the console:

![image](https://user-images.githubusercontent.com/7443/202256410-d81c6114-ba9a-4818-9460-abef1ded8f4b.png)

I believe it's due to these two lines:

https://github.com/reagent-project/reagent-frontend-template/blob/d6e265e92841ad2741ff2dd78df2f8d690ac9bd4/resources/leiningen/new/reagent_frontend/project.clj#L10-L11

If I change them to these:

```clj
[cljsjs/react "17.0.2-0"]
[cljsjs/react-dom "17.0.2-0"]
```

Then the warning goes away.

--- 

Maybe want to wait on React 18 until reagent is ready.

---

Thanks again for this awesome project - I'm off and running, really appreciate you!

**Comment by yogthos** [comment]
Yeah, might be worth rolling back for now and then update once Reagent catches up.

**Comment by yogthos** [comment]
pushed up a version of the template with react rolled back https://github.com/reagent-project/reagent-frontend-template/commit/6d482bf0ae0e3428bd6a513de567484eca454ac4

**Comment by harold** [comment]
This is great! Happy new year. :tada:

**Comment by yogthos** [comment]
Happy new year :)
