### ISSUE TITLE
Figwheel Server: Resource not found

### ISSUE THREAD

**Issue by mkreft** [reagent-project/reagent-frontend-template#2]
- lein new reagent-frontend project
- lein figwheel
- open browser: http://localhost:3449/
  get this : https://monosnap.com/file/vUSqtIm61o2aKemgkVJrR3LAGE9tCi

**Comment by yogthos** [comment]
There's no server in the frontend template, you just use the `resources/public/inde.html` page instead. It's the same as this issue https://github.com/reagent-project/reagent-frontend-template/issues/1
